{
    'name': 'HOBOX Fulfillment',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Fulfillment',
    'summary': '3PL Fulfillment System for HOBOX',
    'author': 'HOBOX',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'stock',
        'delivery',
        'account',
        'purchase',
        'portal',
        'website',
    ],
    'assets': {
        'web.assets_frontend': [
            'hobox_fulfillment/static/src/css/portal.css',
            'hobox_fulfillment/static/src/css/public.css',
        ],
    },
    'data': [
        'security/hobox_security.xml',
        'security/ir.model.access.csv',
        'data/hobox_sequence_data.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/stock_picking_views.xml',
        'views/sale_order_views.xml',
        'views/hobox_platform_integration_views.xml',
        'views/hobox_cod_settlement_views.xml',
        'views/hobox_withdrawal_request_views.xml',
        'views/hobox_registration_views.xml',
        'views/hobox_menu.xml',
        'views/portal_templates.xml',
        'views/public_templates.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
